name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
      NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
      NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
        if: steps.changesets.outputs.hasChangesets == 'false'

      - name: Extract changelog
        run: |
          { awk '/^## [0-9]+\.[0-9]+\.[0-9]+/{ if (p) exit; p = 1; } !p' CHANGELOG.md; 
            awk '/^## [0-9]+\.[0-9]+\.[0-9]+/{ p++; if (p>1) exit } { if (p==1) print $0}' CHANGELOG.md; } > RELEASE.md
        if: steps.changesets.outputs.hasChangesets == 'false'

      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          bodyFile: "RELEASE.md"
          commit: main
          tag: v${{ steps.extract_version.outputs.version }}
        if: steps.changesets.outputs.hasChangesets == 'false'
